# .streamlit/secrets.toml
OPENAI_API_KEY = "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"



