# .streamlit/secrets.toml
OPENAI_API_KEY = "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"

